spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: productModule
        uri: lb://product-service
        predicates:
        - Path=/api/v1/products/**
      - id: stockModule
        uri: ld://stock-service
        predicates:
        - Path=/api/v1/stocks/**
            
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



